export const TODO_CREATE_REQUEST = "TODO_CREATE_REQUEST";
export const TODO_CREATE_SUCCESS = "TODO_CREATE_SUCCESS";
export const TODO_CREATE_FAIL = "TODO_CREATE_FAIL";

export const TODO_LIST_REQUEST = "TODO_LIST_REQUEST";
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS";
export const TODO_LIST_FAIL = "TODO_LIST_FAIL";

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST";
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL";

export const TODO_EDIT_REQUEST = "TODO_EDIT_REQUEST";
export const TODO_EDIT_SUCCESS = "TODO_EDIT_SUCCESS";
export const TODO_EDIT_FAIL = "TODO_EDIT_FAIL";
export const TODO_EDIT_RESET = "TODO_EDIT_RESET";

export const TODO_GETBYID_REQUEST = "TODO_GETBYID_REQUEST";
export const TODO_GETBYID_SUCCESS = "TODO_GETBYID_SUCCESS";
export const TODO_GETBYID_FAIL = "TODO_GETBYID_FAIL";
